#!/bin/bash

MDIR=/tmp/screen-query
pane_id=$(tmux display-message -p '#{pane_id}')
if [[ -r $MDIR/$pane_id.convo ]]; then
    convo_id=$(cat $MDIR/${pane_id}.convo)
    cp $MDIR/${pane_id}.convo $MDIR/last.convo
else
    convo_id=$(cat $MDIR/last.convo)
fi
convo_id=${1:-$convo_id}

echo
{   echo "The user is running a command and sending it to you by piping it through a program called ${0##*/}, here's the last 5 lines of tmux capture-pane, delimited by ----8<----"
    tmux capture-pane -t "${pane_id}" -p | grep -v '^$' | tail -5
    echo "----8<----"
    echo "Here is the output of the command"
    echo "----8<----"
    cat;
} | llm "Briefly respond in less than 1 paragraph" --cid $convo_id | sd
echo -e "\n#$convo_id"

