#!/bin/bash

MDIR=/tmp/screen-query/$UID
pane_id=$(tmux display-message -p '#{pane_id}')
if [[ -r $MDIR/$pane_id.convo ]]; then
    convo_id=$(cat $MDIR/${pane_id}.convo)
    cp $MDIR/${pane_id}.convo $MDIR/last.convo
else
    convo_id=$(cat $MDIR/last.convo)
fi

while getopts ":c:" opt; do
  case $opt in
    c)
      convo_id="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
shift $((OPTIND -1))
if [[ -z "$convo_id" ]]; then
    echo "No conversation ID, no context to add"
    exit 1
fi 

if [ -n "$*" ]; then
  prompt="$*"
else
  prompt=$convo_id
fi

echo -e "\nAdding to #$convo_id ..."
{   echo "The user is running a command and sending it to you.  Here's the last 5 lines of tmux capture-pane, delimited by ----8<----"
    tmux capture-pane -t "${pane_id}" -p | grep -v '^$' | tail -5
    echo "----8<----"
    echo "Here is the output of the command"
    echo "----8<----"
    test -t 0 || cat;
    [[ -r "$1" ]] && cat "$1" 
} | cat #| llm "Briefly respond in less than 1 paragraph" --cid $convo_id | sd

