#!/usr/bin/env bash
# This is an OS X install-time hack
#@@INJECTPATH

VERSION="@@VERSION"

tmp="$(python3 -c "import tempfile;print(tempfile.gettempdir())")"

[[ "$(uname)" == "Darwin" ]] && \
    CONFIG="Library/Application Support" ||\
    CONFIG=".config"
CONFIG="${HOME}/${CONFIG}/sidechat"
SETTINGS="$CONFIG/settings"
[[ -e "$SETTINGS" ]] && source "$SETTINGS"

[[ -r "$CONFIG" ]] || mkdir -p "$CONFIG"
MDIR="$tmp"/sidechat
[[ -d "$MDIR" ]] || (mkdir "$MDIR" && chmod 0777 "$MDIR")
MDIR="$MDIR/$UID"
[[ -d "$MDIR" ]] || mkdir "$MDIR"
MDREAD='sd -c <(echo -e "[style]\nMargin = 4")'

clean() {
    tput cnorm
    exit
}

spinner() {
    tput civis
    trap clean EXIT SIGINT SIGTERM SIGQUIT
    SPINNER="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

    i=0
    while [[ 0 ]]; do
      read -N 1 -t 0.05 tok
      [[ $? != 142 ]] && break
      printf "\e[2K${SPINNER:$i:1}\r"
      (( i = ( i + 1 ) % ${#SPINNER} ))
    done

    {
      echo -en "$tok"
      cat;
    } | ( [[ -n "$1" ]] && "$@" || cat )

    tput cnorm
}
