#!/bin/bash
tmp=$(python3 -c "import tempfile;print(tempfile.gettempdir())")
if [[ -n "$1" ]] ; then 
    perl -0777 -ne 'print join("\0", (split(/\0/, $_))[-'$1'])' /$tmp/sd/$UID/savebrace
    exit
fi

selected=$(perl -0777 -ne 'print join("\0", (split(/\0/, $_))[-40..-1])' /$tmp/sd/$UID/savebrace | fzf --read0 --ansi --multi --no-sort --tac --highlight-line --gap)
if [[ -n "$selected" ]]; then
    if [[ -z "$TMUX" ]]; then
        if command -v xclip &>/dev/null; then
            echo "$selected" | tee /dev/stderr | xclip -i
            echo "\n\n# Also Added to XA_PRIMARY"
        else
            echo "$selected"
        fi
    else
        tmux send-keys -t "$TMUX_PANE" -- "$selected" 
    fi
fi
